import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, symlinkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { buildSdk } from '../adapters/build-sdk.mjs';
import { buildHostChecker } from '../adapters/check-installed.mjs';
import { syncHost } from '../adapters/sync-hosts.mjs';

const TARGET = 'site/pulseboard.js';
const digest = value => createHash('sha256').update(value).digest('hex');

function host({ artifact, lock, checker = buildHostChecker(), local = null }) {
  const root = mkdtempSync(path.join(tmpdir(), 'pulseboard-host-'));
  mkdirSync(path.join(root, 'site'), { recursive: true });
  mkdirSync(path.join(root, 'observatory'), { recursive: true });
  writeFileSync(path.join(root, TARGET), artifact);
  writeFileSync(path.join(root, 'observatory.lock.json'), lock);
  writeFileSync(path.join(root, 'observatory/check.mjs'), checker);
  if (local) writeFileSync(path.join(root, 'observatory/check.local.mjs'), local);
  return root;
}
const lockFor = (sha256, extra = {}) => JSON.stringify({ version: '0.2.0', sdk: '0.0.0', source: 'Chris0Jeky/Pulseboard:observatory',
  installs: { [TARGET]: { project: 'portfolio', release: 'unattributed', sha256, ...extra } } }, null, 2) + '\n';

test('a stale pristine artifact is rebuilt, the lock follows, and a second run changes nothing', t => {
  const root = host({ artifact: buildSdk('mdviewer'), lock: lockFor('0'.repeat(64)) });
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const first = syncHost(root);
  const fresh = buildSdk('portfolio');
  assert.equal(readFileSync(path.join(root, TARGET), 'utf8'), fresh);
  assert.deepEqual(first.changed.sort(), ['observatory.lock.json', TARGET].sort());
  assert.equal(first.hostCheck.ok, true);
  const lock = JSON.parse(readFileSync(path.join(root, 'observatory.lock.json'), 'utf8'));
  assert.equal(lock.installs[TARGET].sha256, digest(fresh));
  assert.equal(lock.sdk, first.sdk);
  const before = readFileSync(path.join(root, 'observatory.lock.json'), 'utf8');
  assert.deepEqual(syncHost(root).changed, []);
  assert.equal(readFileSync(path.join(root, 'observatory.lock.json'), 'utf8'), before);
});

test('a lock whose values are current keeps its own formatting', t => {
  const fresh = buildSdk('portfolio');
  const version = /pulseboard-sdk (\S+) for/.exec(fresh)[1];
  const compact = JSON.stringify({ version: '0.2.0', sdk: version, source: 'Chris0Jeky/Pulseboard:observatory',
    installs: { [TARGET]: { project: 'portfolio', release: 'unattributed', sha256: digest(fresh), builds: ['a', 'b'] } } });
  const root = host({ artifact: fresh, lock: compact });
  t.after(() => rmSync(root, { recursive: true, force: true }));
  assert.deepEqual(syncHost(root).changed, []);
  assert.equal(readFileSync(path.join(root, 'observatory.lock.json'), 'utf8'), compact);
});

test('an edited artifact is refused, never overwritten', t => {
  const root = host({ artifact: 'console.log("edited by hand");\n', lock: lockFor('0'.repeat(64)) });
  t.after(() => rmSync(root, { recursive: true, force: true }));
  assert.throws(() => syncHost(root), /not an unedited Pulseboard SDK artifact/);
  assert.equal(readFileSync(path.join(root, TARGET), 'utf8'), 'console.log("edited by hand");\n');
});

test('a host policy that refuses the update is reported for a person, not hidden', t => {
  const root = host({ artifact: buildSdk('mdviewer'), lock: lockFor('0'.repeat(64)),
    local: "export default function check() { throw new Error('pinned SDK 3.1.0'); }\n" });
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const result = syncHost(root);
  assert.equal(result.hostCheck.ok, false);
  assert.match(result.hostCheck.detail, /pinned SDK 3\.1\.0/);
});

test('a hand-written checker is never replaced; a stale generated one is', t => {
  const handWritten = '// Host-specific checks\nconsole.log("ok");\n';
  const kept = host({ artifact: buildSdk('portfolio'), lock: lockFor(digest(buildSdk('portfolio'))), checker: handWritten });
  const stale = host({ artifact: buildSdk('portfolio'), lock: lockFor(digest(buildSdk('portfolio'))),
    checker: buildHostChecker().replace('Do not edit this file.', 'Do not edit this file.\n * (older build)') });
  t.after(() => { rmSync(kept, { recursive: true, force: true }); rmSync(stale, { recursive: true, force: true }); });
  syncHost(kept);
  assert.equal(readFileSync(path.join(kept, 'observatory/check.mjs'), 'utf8'), handWritten);
  assert.ok(syncHost(stale).changed.includes('observatory/check.mjs'));
  assert.equal(readFileSync(path.join(stale, 'observatory/check.mjs'), 'utf8'), buildHostChecker());
});

test('no-run mode rebuilds from data only: the host check never executes', t => {
  const marker = 'check-ran.txt';
  const root = host({ artifact: buildSdk('mdviewer'), lock: lockFor('0'.repeat(64)),
    local: `import { writeFileSync } from 'node:fs'; writeFileSync(${JSON.stringify(marker)}, 'x'); export default function check() {}\n` });
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const result = syncHost(root, { run: false });
  assert.equal(result.hostCheck.skipped, true);
  assert.ok(result.changed.includes(TARGET));
  assert.equal(readFileSync(path.join(root, TARGET), 'utf8'), buildSdk('portfolio'));
  assert.throws(() => readFileSync(path.join(root, marker)), /ENOENT/);
});

test('no-run mode refreshes a stale generated checker only when told it passed', t => {
  const stale = buildHostChecker().replace('Do not edit this file.', 'Do not edit this file.\n * (older build)');
  const make = () => host({ artifact: buildSdk('portfolio'), lock: lockFor(digest(buildSdk('portfolio'))), checker: stale });
  const kept = make(), refreshed = make();
  t.after(() => { rmSync(kept, { recursive: true, force: true }); rmSync(refreshed, { recursive: true, force: true }); });
  assert.ok(!syncHost(kept, { run: false }).changed.includes('observatory/check.mjs'));
  assert.equal(readFileSync(path.join(kept, 'observatory/check.mjs'), 'utf8'), stale);
  assert.ok(syncHost(refreshed, { run: false, refreshChecker: true }).changed.includes('observatory/check.mjs'));
  assert.equal(readFileSync(path.join(refreshed, 'observatory/check.mjs'), 'utf8'), buildHostChecker());
});

test('install targets in dot-folders, with a backslash, or through a symlink, are refused', t => {
  const dotted = host({ artifact: buildSdk('portfolio'), lock: lockFor('0'.repeat(64)).replace(TARGET, '.git/config') });
  t.after(() => rmSync(dotted, { recursive: true, force: true }));
  assert.throws(() => syncHost(dotted, { run: false }), /Refusing path \.git\/config/);
  const slashed = host({ artifact: buildSdk('portfolio'), lock: lockFor('0'.repeat(64)).replace(TARGET, 'x\\\\y/config') });
  t.after(() => rmSync(slashed, { recursive: true, force: true }));
  assert.throws(() => syncHost(slashed, { run: false }), /Refusing path x\\y\/config/);
  const linked = host({ artifact: buildSdk('portfolio'), lock: lockFor('0'.repeat(64)).replace(TARGET, 'x/config') });
  t.after(() => rmSync(linked, { recursive: true, force: true }));
  mkdirSync(path.join(linked, 'real'), { recursive: true });
  try { symlinkSync(path.join(linked, 'real'), path.join(linked, 'x'), 'dir'); }
  catch (error) { if (error.code === 'EPERM') { t.skip('this host cannot create symlinks'); return; } throw error; }
  assert.throws(() => syncHost(linked, { run: false }), /Refusing symlinked path x\/config/);
});
