import { readFileSync, writeFileSync, mkdirSync, lstatSync, realpathSync } from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { assertArtifactShape, isReservedInstallTarget } from './build-embed.mjs';
import { projects } from '../src/projects.mjs';

/** Builds the per-project classic-script SDK artifact (USAGE_PLAN "The SDK"; docs/SDK.md).
 * The output is deterministic: no timestamps or commit ids, LF only, and a header naming the SDK version
 * and the SHA-256 of the body that follows it, so a host (or this builder) can tell a pristine artifact from an edited one. */
export const SDK_COLLECTOR = 'https://pulseboard-observatory.commit-atlas.workers.dev';
const VERSION = '3.0.0';
const HEADER = /^\/\* SPDX-License-Identifier: GPL-3\.0-only\n \* pulseboard-sdk (\S+) for ([a-z0-9-]+)\. Generated by observatory\/adapters\/build-sdk\.mjs; do not edit\.\n \* sha256 of the body below: ([0-9a-f]{64}) \*\/\n/;
const digest = value => createHash('sha256').update(value).digest('hex');

export function buildSdk(id, { release } = {}) {
  if (!Object.hasOwn(projects, id)) throw new Error('Register the project in src/projects.mjs first');
  const project = projects[id];
  if (!project.origin) throw new Error('This project deliberately has no public collection origin');
  const releases = project.releases;
  const chosen = release ?? releases[releases.length - 1];
  if (typeof chosen !== 'string' || !releases.includes(chosen)) throw new Error('Release must be one of the registered releases for ' + id + ': ' + releases.join(', '));
  // Only the client-side contract is published: probe URLs, markers and budgets stay operator data.
  const config = { id, label: project.label, origin: project.origin, collector: SDK_COLLECTOR, release: chosen, route: 'home',
    project: { events: project.events, routes: project.routes, releases } };
  const json = JSON.stringify(config).replaceAll('<', '\\u003c');
  const source = readFileSync(new URL('../sdk/pulseboard-sdk.mjs', import.meta.url), 'utf8').replaceAll('\r\n', '\n')
    .replace(/^import .*;\n/gm, '').replace(/^export /gm, '');
  const body = `(function () {
'use strict';
if (globalThis.Pulseboard && globalThis.Pulseboard.version) return;
${source}
const config = ${json};
let sdk = createPulseboard(config, globalThis);
const mount = () => sdk.mount();
globalThis.Pulseboard = Object.freeze({
  version: SDK_VERSION,
  route: name => sdk.route(name),
  count: event => sdk.count(event),
  track: (name, props) => sdk.track(name, props),
  consent: Object.freeze({ get: () => sdk.consent.get(), set: choice => sdk.consent.set(choice), open: () => sdk.consent.open() }),
});
if (globalThis.document && globalThis.document.readyState === 'loading') globalThis.document.addEventListener('DOMContentLoaded', mount, { once: true }); else mount();
globalThis.addEventListener?.('pageshow', event => { if (event.persisted && !sdk.resume()) { sdk = createPulseboard(config, globalThis); mount(); } });
})();
`;
  const content = `/* SPDX-License-Identifier: GPL-3.0-only
 * pulseboard-sdk ${VERSION} for ${id}. Generated by observatory/adapters/build-sdk.mjs; do not edit.
 * sha256 of the body below: ${digest(body)} */
${body}`;
  assertArtifactShape(content);
  new vm.Script(content);
  return content;
}

/** True when `content` is an unedited artifact from this builder: the header hash matches the body. */
export function isPristineSdk(content) {
  const text = String(content);
  const match = HEADER.exec(text);
  return !!match && digest(text.slice(match[0].length)) === match[3];
}

/** Write inside `root` only: relative target, no `..`, no symlinked parent leaving the tree, no symlink target,
 * no installer-reserved path, and never over a file that is not a pristine SDK artifact. */
export function writeSdk(id, root, target, options = {}) {
  const base = realpathSync(root), full = path.resolve(base, target);
  if (path.isAbsolute(target) || !full.startsWith(base + path.sep) || target.split(/[\\/]/).includes('..')) throw new Error('Target must be a relative path inside the repository');
  if (isReservedInstallTarget(target, base)) throw new Error('Target is reserved for Observatory installer metadata');
  let parent = path.dirname(full);
  while (!lstatSync(parent, { throwIfNoEntry: false })) parent = path.dirname(parent);
  let resolved; try { resolved = realpathSync(parent); } catch { throw new Error('Symlink leaves repository'); }
  if (resolved !== base && !resolved.startsWith(base + path.sep)) throw new Error('Symlink leaves repository');
  const stat = lstatSync(full, { throwIfNoEntry: false });
  if (stat?.isSymbolicLink()) throw new Error('Refusing a symlink target');
  if (stat && (!stat.isFile() || !isPristineSdk(readFileSync(full, 'utf8').replaceAll('\r\n', '\n')))) throw new Error('Existing file is not an unedited Pulseboard SDK artifact; refusing overwrite');
  const content = buildSdk(id, options);
  mkdirSync(path.dirname(full), { recursive: true });
  writeFileSync(full, content);
  const sha256 = digest(readFileSync(full));
  if (sha256 !== digest(content)) throw new Error('Generated artifact changed while writing');
  return { project: id, target, sha256, release: JSON.parse(/^const config = (\{.*\});$/m.exec(content)[1]).release };
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url))) {
  const [id, root, target, release] = process.argv.slice(2);
  try {
    if (!id) { console.error('Usage: npm run build:sdk -- PROJECT [REPOSITORY_ROOT RELATIVE_OUTPUT [RELEASE]]'); process.exitCode = 2; }
    else if (!root) process.stdout.write(buildSdk(id));
    else if (!target) { console.error('Give both REPOSITORY_ROOT and RELATIVE_OUTPUT, or neither to print the artifact'); process.exitCode = 2; }
    else console.log(JSON.stringify(writeSdk(id, root, target, release ? { release } : {}), null, 2));
  } catch (error) { console.error(error.message); process.exitCode = 1; }
}
