import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { buildSdk, writeSdk } from './build-sdk.mjs';
import { buildHostChecker, HOST_CHECKER } from './check-installed.mjs';

/** Brings one host repository's installed SDK artifacts up to date with this checkout (owner decision 2026-09-27,
 * HUMAN_TODO q-29): every install listed in its observatory.lock.json is rebuilt from src/projects.mjs and the SDK,
 * the lock's hashes and SDK version follow, and the generated host checker is refreshed only when the new checker
 * passes on that host. Nothing outside the lock, its installs and the checker is ever written. */
const LOCK = 'observatory.lock.json';
const digest = value => createHash('sha256').update(value).digest('hex');
const lf = value => value.replaceAll('\r\n', '\n');
const GENERATED = /^\/\* SPDX-License-Identifier: GPL-3\.0-only\n \* Generated by Pulseboard Observatory\. Do not edit this file\./;
const sdkVersion = content => /^ \* pulseboard-sdk (\S+) for /m.exec(content)?.[1] ?? null;

function hostCheck(root) {
  try { execFileSync(process.execPath, [path.join(root, HOST_CHECKER)], { cwd: root, stdio: 'pipe', timeout: 60_000 }); return { ok: true }; }
  catch (error) {
    const lines = String(error.stderr || error.message).split('\n').map(line => line.trim()).filter(Boolean);
    return { ok: false, detail: lines.find(line => /^[A-Za-z]*Error(?: \[[A-Z_]+\])?: /.test(line)) ?? lines.at(-1) ?? 'unknown failure' };
  }
}

export function syncHost(root) {
  const lockPath = path.join(root, LOCK);
  const lockText = readFileSync(lockPath, 'utf8');
  const lock = JSON.parse(lockText);
  if (!lock.installs || typeof lock.installs !== 'object' || Array.isArray(lock.installs)) throw new Error('Lock has no installs map');
  const changed = [], allowed = [LOCK, HOST_CHECKER];
  let version = null, dirty = false;
  for (const [target, entry] of Object.entries(lock.installs)) {
    allowed.push(target);
    const options = typeof entry.release === 'string' ? { release: entry.release } : {};
    const fresh = buildSdk(entry.project, options);
    version = sdkVersion(fresh);
    const full = path.join(root, target);
    const current = existsSync(full) ? lf(readFileSync(full, 'utf8')) : null;
    if (current !== fresh) { writeSdk(entry.project, root, target, options); changed.push(target); }
    // Builders and host checkers hash the LF text, so a CRLF checkout keeps the digest the lock pins.
    const sha256 = digest(lf(readFileSync(full, 'utf8')));
    if (entry.sha256 !== sha256) { entry.sha256 = sha256; dirty = true; }
    if (typeof entry.sdk === 'string' && entry.sdk !== version) { entry.sdk = version; dirty = true; }
  }
  if (typeof lock.sdk === 'string' && version && lock.sdk !== version) { lock.sdk = version; dirty = true; }
  // Rewrite the lock only when a value moved, so a host's own formatting survives routine runs.
  if (dirty) {
    const eol = lockText.includes('\r\n') ? '\r\n' : '\n';
    writeFileSync(lockPath, JSON.stringify(lock, null, 2).replaceAll('\n', eol) + eol); changed.push(LOCK);
  }
  // A host whose own policy refuses the update (for example a pinned SDK version) is reported, not hidden: the
  // workflow then opens its pull request for a person instead of merging it.
  const after = hostCheck(root);
  if (!after.ok) return { root, sdk: version, changed: [...new Set(changed)], allowed, hostCheck: after };
  // Refresh the generated checker only when the new one also passes here; an older host keeps its working checker.
  const checkerPath = path.join(root, HOST_CHECKER);
  if (existsSync(checkerPath)) {
    const old = readFileSync(checkerPath, 'utf8'), next = buildHostChecker();
    // A hand-written checker carries the host's own assertions; only the generated one is ever replaced.
    if (GENERATED.test(lf(old)) && lf(old) !== next) {
      writeFileSync(checkerPath, next);
      if (hostCheck(root).ok) changed.push(HOST_CHECKER); else writeFileSync(checkerPath, old);
    }
  }
  return { root, sdk: version, changed: [...new Set(changed)], allowed, hostCheck: { ok: true } };
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url))) {
  const root = process.argv[2];
  try {
    if (!root) { console.error('Usage: node adapters/sync-hosts.mjs HOST_REPOSITORY_ROOT'); process.exitCode = 2; }
    else console.log(JSON.stringify(syncHost(path.resolve(root)), null, 2));
  } catch (error) { console.error(error.message); process.exitCode = 1; }
}
