import { readFileSync, writeFileSync, existsSync, lstatSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { buildSdk, writeSdk } from './build-sdk.mjs';
import { buildHostChecker, HOST_CHECKER } from './check-installed.mjs';

/** Brings one host repository's installed SDK artifacts up to date with this checkout (owner decision 2026-09-27,
 * HUMAN_TODO q-29): every install listed in its observatory.lock.json is rebuilt from src/projects.mjs and the SDK,
 * the lock's hashes and SDK version follow, and the generated host checker is refreshed only when the new checker
 * passes on that host. Nothing outside the lock, its installs and the checker is ever written.
 *
 * Two modes, used by .github/workflows/sync-sites.yml:
 * - run (default): also executes the host's own observatory/check.mjs. Only for a job that holds no secrets.
 * - { run: false }: never executes host code; the site repository is read as data only. The caller says whether
 *   the refreshed generated checker passed (learned from a run-mode job), so the token-holding job rebuilds every
 *   byte itself instead of trusting files produced next to host code. */
const LOCK = 'observatory.lock.json';
const digest = value => createHash('sha256').update(value).digest('hex');
const lf = value => value.replaceAll('\r\n', '\n');
const GENERATED = /^\/\* SPDX-License-Identifier: GPL-3\.0-only\n \* Generated by Pulseboard Observatory\. Do not edit this file\./;
const sdkVersion = content => /^ \* pulseboard-sdk (\S+) for /m.exec(content)?.[1] ?? null;

/** Every path this tool writes is a plain relative path with no dot-segment (so never .git, .github or ..), and no
 * existing component of it is a symlink: a host cannot route a write into repository metadata or out of the tree.
 * Lock paths use forward slashes only; a backslash is refused on every platform, because Linux reads it as part of a
 * file name and the symlink walk below would then miss the component it hides (#158). */
export function assertPlainPath(root, relative) {
  const parts = String(relative).split('/');
  if (String(relative).includes('\\') || path.isAbsolute(relative) || parts.some(part => part === '' || part.startsWith('.'))) throw new Error('Refusing path ' + relative);
  for (let i = 1; i <= parts.length; i++) {
    if (lstatSync(path.join(root, ...parts.slice(0, i)), { throwIfNoEntry: false })?.isSymbolicLink()) throw new Error('Refusing symlinked path ' + relative);
  }
}

function hostCheck(root) {
  try { execFileSync(process.execPath, [path.join(root, HOST_CHECKER)], { cwd: root, stdio: 'pipe', timeout: 60_000 }); return { ok: true }; }
  catch (error) {
    const lines = String(error.stderr || error.message).split('\n').map(line => line.trim()).filter(Boolean);
    return { ok: false, detail: lines.find(line => /^[A-Za-z]*Error(?: \[[A-Z_]+\])?: /.test(line)) ?? lines.at(-1) ?? 'unknown failure' };
  }
}

export function syncHost(root, { run = true, refreshChecker = false } = {}) {
  assertPlainPath(root, LOCK);
  const lockPath = path.join(root, LOCK);
  const lockText = readFileSync(lockPath, 'utf8');
  const lock = JSON.parse(lockText);
  if (!lock.installs || typeof lock.installs !== 'object' || Array.isArray(lock.installs)) throw new Error('Lock has no installs map');
  const changed = [], allowed = [LOCK, HOST_CHECKER];
  let version = null, dirty = false;
  for (const [target, entry] of Object.entries(lock.installs)) {
    assertPlainPath(root, target);
    allowed.push(target);
    const options = typeof entry.release === 'string' ? { release: entry.release } : {};
    const fresh = buildSdk(entry.project, options);
    version = sdkVersion(fresh);
    const full = path.join(root, target);
    const current = existsSync(full) ? lf(readFileSync(full, 'utf8')) : null;
    if (current !== fresh) { writeSdk(entry.project, root, target, options); changed.push(target); }
    // Builders and host checkers hash the LF text, so a CRLF checkout keeps the digest the lock pins.
    const sha256 = digest(lf(readFileSync(full, 'utf8')));
    if (entry.sha256 !== sha256) { entry.sha256 = sha256; dirty = true; }
    if (typeof entry.sdk === 'string' && entry.sdk !== version) { entry.sdk = version; dirty = true; }
  }
  if (typeof lock.sdk === 'string' && version && lock.sdk !== version) { lock.sdk = version; dirty = true; }
  // Rewrite the lock only when a value moved, so a host's own formatting survives routine runs.
  if (dirty) {
    const eol = lockText.includes('\r\n') ? '\r\n' : '\n';
    writeFileSync(lockPath, JSON.stringify(lock, null, 2).replaceAll('\n', eol) + eol); changed.push(LOCK);
  }
  const result = extra => ({ root, sdk: version, changed: [...new Set(changed)], allowed, ...extra });
  const checkerPath = path.join(root, HOST_CHECKER);
  const staleGenerated = () => {
    if (!existsSync(checkerPath)) return null;
    assertPlainPath(root, HOST_CHECKER);
    const old = readFileSync(checkerPath, 'utf8'), next = buildHostChecker();
    // A hand-written checker carries the host's own assertions; only the generated one is ever replaced.
    return GENERATED.test(lf(old)) && lf(old) !== next ? { old, next } : null;
  };
  if (!run) {
    const stale = refreshChecker ? staleGenerated() : null;
    if (stale) { writeFileSync(checkerPath, stale.next); changed.push(HOST_CHECKER); }
    return result({ hostCheck: { ok: null, skipped: true }, checkerRefreshed: Boolean(stale) });
  }
  // A host whose own policy refuses the update (for example a pinned SDK version) is reported, not hidden: the
  // workflow then opens its pull request for a person instead of merging it.
  const after = hostCheck(root);
  if (!after.ok) return result({ hostCheck: after, checkerRefreshed: false });
  // Refresh the generated checker only when the new one also passes here; an older host keeps its working checker.
  const stale = staleGenerated();
  let refreshed = false;
  if (stale) {
    writeFileSync(checkerPath, stale.next);
    if (hostCheck(root).ok) { changed.push(HOST_CHECKER); refreshed = true; } else writeFileSync(checkerPath, stale.old);
  }
  return result({ hostCheck: { ok: true }, checkerRefreshed: refreshed });
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url))) {
  const [root, ...flags] = process.argv.slice(2);
  try {
    if (!root || flags.some(flag => !['--no-run', '--refresh-checker'].includes(flag))) {
      console.error('Usage: node adapters/sync-hosts.mjs HOST_REPOSITORY_ROOT [--no-run [--refresh-checker]]'); process.exitCode = 2;
    } else console.log(JSON.stringify(syncHost(path.resolve(root), { run: !flags.includes('--no-run'), refreshChecker: flags.includes('--refresh-checker') }), null, 2));
  } catch (error) { console.error(error.message); process.exitCode = 1; }
}
